# Generated by Django 5.2.11 on 2026-02-05 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('name_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_hindi', models.TextField(blank=True, null=True)),
                ('benefit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eligibility_rules', models.JSONField(default=dict)),
                ('required_documents', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'db_table': 'schemes',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
