# Generated by Django 5.2.11 on 2026-02-05 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('land_certificate', 'Land Certificate'), ('bank_passbook', 'Bank Passbook'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('other', 'Other')], max_length=50)),
                ('document_url', models.URLField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
