# Generated by Django 5.2.11 on 2026-02-05 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('land_size', models.DecimalField(decimal_places=2, default=0, help_text='Land size in acres', max_digits=10)),
                ('crop_type', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('marathi', 'Marathi'), ('english', 'English')], default='hindi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'db_table': 'farmers',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
